name: Simple Action

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - staging
    
jobs:
  hello-world:
    name: Call Hello Workflow!
    uses: m-mattei/github-actions-test/.github/workflows/hello-world.yml@main
    with:
      message: 'Hello!'
      
