name: Simple Action

on: [push, workflow_dispatch]


jobs:
    hello-world:
      uses: m-mattei/github-actions-test/.github/workflows/hello.yml@main
      with:
        message: 'Hello World'
      
